### ISSUE TITLE
Some of the spacing is off on the new August 15 2020 discord update.

### ISSUE THREAD

**Issue by RavenousSix** [fluffingtons/revert-discord#7]
Would love it if some minor issues were fixed with this theme. It's the last good one left that still works. Some of the emotes when you react to something are spaced a lot lower than they should be. Any sort of fix would be appreciated.

Thanks!

**Comment by joshodude** [comment]
Adding on to this issue. There's weird spacing between profile picture and message now. I tried disabling all of my plugins and other themes except Revert Discord and I still have the same issue. [https://imgur.com/a/Wk0POll](https://imgur.com/a/Wk0POll)

- Revert Theme 18/06/2020
- BBD 0.3.5
- Stable 65349 (99df168)

**Comment by Kaydax** [comment]
Put this css inside of your custom css to fix the padding issues:
```css
div[class*="message-"][class*="wrapper-"] {
  padding: 0;
  padding-left: 80px!important;
  padding-right: 10px!important;
}

div[class*="cozyMessage"] > div[class*="contents"] > div[class*="markup"] {
  padding-left: 80px!important;
  margin-left: -80px!important;
}
```

**Comment by Kaydax** [comment]
If you want less spacing between the reactions / embeds and messages use this:
```css
div[class*="cozyMessage"] > div[class*="container"]:not([class*="button"]) {
  padding-top: 8px;
  padding-bottom: 8px;
  grid-row-gap: 8px;
}
```
